version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ../../
      dockerfile: ci/docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/0
      - MYSQL_URL=mysql://root:password@mysql:3306/autotest
    depends_on:
      - mongodb
      - redis
      - mysql
    volumes:
      - ../../:/app
    networks:
      - app-network

  # MongoDB服务
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Redis服务
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # MySQL服务
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=autotest
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:
  mysql_data:

networks:
  app-network:
    driver: bridge 