name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Autotest@2024
          MYSQL_DATABASE: autotest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
      mongodb:
        image: mongo:6.0
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: Autotest@2024
        ports:
          - 27017:27017
      
      redis:
        image: redis:6.2
        env:
          REDIS_PASSWORD: Autotest@2024
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements/dev.txt
        
    - name: Run tests
      run: |
        cd backend
        pytest tests/ -v
      env:
        MYSQL_HOST: localhost
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: Autotest@2024
        MYSQL_DATABASE: autotest
        MONGODB_URI: mongodb://admin:Autotest@2024@localhost:27017
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        REDIS_PASSWORD: Autotest@2024

  frontend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        
    - name: Run tests
      run: |
        cd frontend
        npm run test:unit
        
    - name: Build
      run: |
        cd frontend
        npm run build 