name: 代码检查

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-check:
    name: 后端代码检查
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置Python环境
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy black isort bandit safety
        pip install -r backend/requirements.txt
        
    - name: 代码格式检查 (Black)
      run: |
        black --check backend/
        
    - name: 导入顺序检查 (isort)
      run: |
        isort --check-only backend/
        
    - name: 类型检查 (mypy)
      run: |
        mypy backend/
        
    - name: 代码风格检查 (flake8)
      run: |
        flake8 backend/ --max-line-length=100 --extend-ignore=E203
        
    - name: 安全漏洞检查 (bandit)
      run: |
        bandit -r backend/ -ll
        
    - name: 依赖安全检查 (safety)
      run: |
        safety check -r backend/requirements.txt

  frontend-check:
    name: 前端代码检查
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置Node.js环境
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: 安装依赖
      run: |
        cd frontend
        npm ci
        
    - name: ESLint检查
      run: |
        cd frontend
        npm run lint
        
    - name: TypeScript类型检查
      run: |
        cd frontend
        npm run type-check
        
    - name: 代码格式检查 (Prettier)
      run: |
        cd frontend
        npm run format:check
        
    - name: 依赖安全检查
      run: |
        cd frontend
        npm audit 